[project]
name = "airflow-metaflow-lineage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "apache-airflow>=3.0.2",
    "apache-airflow-providers-amazon>=9.9.0",
]

[dependency-groups]
cdk = [
    "aws-cdk-lib>=2.202.0",
    "constructs>=10.4.2",
]

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"
